# Generated by Django 2.2.1 on 2019-05-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=50)),
                ('b_pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=30)),
                ('h_gender', models.BooleanField()),
                ('h_content', models.CharField(max_length=1000)),
                ('h_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbtest.BookInfo')),
            ],
        ),
    ]
